# ════════════════════════════════════════════════════════════
# Pipeline: Users -> Snowflake
# Source: open-source-data (GitHub raw URL)
# ════════════════════════════════════════════════════════════
apiVersion: mako/v1
kind: Pipeline

pipeline:
  name: users-to-snowflake
  description: "Ingest users data from GitHub with PII masking and load to Snowflake"
  owner: data-team

  source:
    type: file
    config:
      path: https://raw.githubusercontent.com/Stefen-Taime/open-source-data/main/user/json/users.json
      format: json

  transforms:
    - name: pii_hash
      type: hash_fields
      fields: [email, password, social_insurance_number, phone_number]

    - name: drop_sensitive
      type: drop_fields
      fields: [avatar]

  sink:
    type: snowflake
    database: ANALYTICS
    schema: RAW
    table: USERS
    flatten: true
    config:
      account: REPLACE_WITH_YOUR_ACCOUNT
      user: REPLACE_WITH_YOUR_USER
      warehouse: COMPUTE_WH
      role: ACCOUNTADMIN
